name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Download Blender
      run: sudo snap install blender --classic

    - name: Export objects
      run: /snap/bin/blender RoadsPathsFences.blend --background --python export.py

    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='export.py' . ./release
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.AUTOTAG_TOKEN }}
        REPO_OWNER: flynsarmy
        DEFAULT_BUMP: minor
        WITH_V: true
        INITIAL_VERSION: 0.0.0