name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download Blender
      run: sudo snap install blender --classic

    - name: Export objects
      run: /snap/bin/blender RoadsPathsFences.blend --background --python export.py

    - name: Zip Folder
      run: zip -r release.zip *.blend fbx obj gltf

    # - name: Create Release Folder
    #   run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='export.py' . ./release

    # - name: Switch to Release Folder
    #   run: |
    #     ls -la release


    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.AUTOTAG_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          release.zip