name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download Blender
      run: sudo snap install blender --classic

    - name: Export objects
      run: /snap/bin/blender RoadsPathsFences.blend --background --python export.py

    - name: Zip Folder
      run: zip -r release.zip . -x ".git/*"

    - name: Release to Github
      run: echo "Release"